GET http://localhost:5000/api/v1/authors/06c54898-0388-4af1-a7f9-018b50892a23/citations
Content-Type: application/json

###

POST http://localhost:5000/api/v1/authors/06c54898-0388-4af1-a7f9-018b50892a23/citations
Content-Type: application/json

{
    "author": "Author Name 2",
    "text": "Citation Text 2"
}

###

PUT http://localhost:5000/api/v1/citations/6bd58443-c5c6-4cb7-b02d-27ed9cb164d4
Content-Type: application/json

{
    "author": "Updated Author Name",
    "text": "Updated Citation Text"
}

###

DELETE http://localhost:5000/api/v1/citations/6bd58443-c5c6-4cb7-b02d-27ed9cb164d4
Content-Type: application/json

###
