GET http://localhost:5001/api/v1/users/58911671-b745-4b90-b9ff-c0a073a8a5c1/reviews
Content-Type: application/json

###

POST http://localhost:5001/api/v1/users/3bfaa0f0-89a8-4f3d-9860-b5b462467baf/reviews
Content-Type: application/json

{
    "text": "Review Text"
}

###

PUT http://localhost:5001/api/v1/reviews/ac7e8ca5-bb72-405a-bad9-5c017359dafd
Content-Type: application/json

{
    "text": "Updated Review Text"
}

###

DELETE http://localhost:5001/api/v1/reviews/ac7e8ca5-bb72-405a-bad9-5c017359dafd
Content-Type: application/json

###
