GET http://localhost:5000/api/v1/authors
Content-Type: application/json

###

GET http://localhost:5000/api/v1/authors/f46709fa-b4da-4fba-9b68-b1ade55088be/quotes
Content-Type: application/json

###

POST http://localhost:5000/api/v1/authors
Content-Type: application/json

{
    "name": "Author 3"
}

###

PUT http://localhost:5000/api/v1/authors/6d34ee3a-49b0-44e2-b5aa-95c3c508811b
Content-Type: application/json

{
    "name": "Updated Author 4"
}

###

DELETE http://localhost:5000/api/v1/authors/6d34ee3a-49b0-44e2-b5aa-95c3c508811b
Content-Type: application/json

###
