
GET http://localhost:5001/api/v1/users
Content-Type: application/json

###

GET http://localhost:5001/api/v1/users/a2c0ec46-7e5f-41c8-a3e3-1ee5545a30be
Content-Type: application/json

###

POST http://localhost:5001/api/v1/users
Content-Type: application/json

{
    "email": "2new_user@example.com",
    "password": "2password",
    "first_name": "2New",
    "last_name": "2User"
}

###


PUT http://localhost:5000/api/v1/categories/6d34ee3a-49b0-44e2-b5aa-95c3c508811b
Content-Type: application/json

{
    "name": "Updated Category 4"
}

###

DELETE http://localhost:5001/api/v1/users/f7cee44c-ecd0-4d16-abd4-d39e800803e5
Content-Type: application/json

###