#!/usr/bin/python3

from models.engine.db_storage import DBStorage
from models.quote import Quote
from models.category import Category

# Initialize the DBStorage engine
db_storage = DBStorage()
db_storage.reload()

# Create instances of models for categories with quotes
categories = [
    Category(name="Motivational", quotes=[
        Quote(text="Believe you can and you're halfway there.", author="Theodore Roosevelt"),
        Quote(text="The only limit to our realization of tomorrow will be our doubts of today.", author="Franklin D. Roosevelt"),
        Quote(text="The best way to predict the future is to create it.", author="Peter Drucker"),
        Quote(text="Success is not final, failure is not fatal: It is the courage to continue that counts.", author="Winston Churchill"),
        Quote(text="Success consists of going from failure to failure without loss of enthusiasm.", author="Winston Churchill"),
        Quote(text="The only way to do great work is to love what you do.", author="Steve Jobs"),
        Quote(text="You are never too old to set another goal or to dream a new dream.", author="C.S. Lewis"),
        Quote(text="It's not what you look at that matters, it's what you see.", author="Henry David Thoreau"),
        Quote(text="The biggest risk is not taking any risk. In a world that's changing really quickly, the only strategy that is guaranteed to fail is not taking risks.", author="Mark Zuckerberg"),
        Quote(text="You miss 100% of the shots you don't take.", author="Wayne Gretzky"),
        Quote(text="The only true way to fail is to not try at all.", author="Unknown"),
        Quote(text="Opportunities don't happen, you create them.", author="Chris Grosser"),
        Quote(text="The only way to achieve the impossible is to believe it is possible.", author="Charles Kingsleigh"),
        Quote(text="Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author="Albert Schweitzer"),
        Quote(text="The road to success and the road to failure are almost exactly the same.", author="Colin R. Davis"),
        Quote(text="The only place where success comes before work is in the dictionary.", author="Vidal Sassoon"),
        Quote(text="It always seems impossible until it is done.", author="Nelson Mandela"),
        Quote(text="Success is not in what you have, but who you are.", author="Bo Bennett"),
        Quote(text="The only limit to our realization of tomorrow is our doubts of today.", author="Franklin D. Roosevelt"),
        Quote(text="In order to succeed, we must first believe that we can.", author="Nikos Kazantzakis"),
        Quote(text="Don't watch the clock; do what it does. Keep going.", author="Sam Levenson"),
        Quote(text="The only way to achieve the impossible is to believe it is possible.", author="Charles Kingsleigh"),
        Quote(text="Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author="Albert Schweitzer"),
    ]),
    Category(name="Inspiration", quotes=[
        Quote(text="The only way to do great work is to love what you do.", author="Steve Jobs"),
        Quote(text="You are never too old to set another goal or to dream a new dream.", author="C.S. Lewis"),
        Quote(text="It's not what you look at that matters, it's what you see.", author="Henry David Thoreau"),
        Quote(text="The biggest risk is not taking any risk. In a world that's changing really quickly, the only strategy that is guaranteed to fail is not taking risks.", author="Mark Zuckerberg"),
        Quote(text="You miss 100% of the shots you don't take.", author="Wayne Gretzky"),
        Quote(text="Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author="Albert Schweitzer"),
        Quote(text="The only limit to our realization of tomorrow is our doubts of today.", author="Franklin D. Roosevelt"),
        Quote(text="In order to succeed, we must first believe that we can.", author="Nikos Kazantzakis"),
        Quote(text="Don't watch the clock; do what it does. Keep going.", author="Sam Levenson"),
        Quote(text="The only way to achieve the impossible is to believe it is possible.", author="Charles Kingsleigh"),
        Quote(text="Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author="Albert Schweitzer"),
        Quote(text="The only limit to our realization of tomorrow is our doubts of today.", author="Franklin D. Roosevelt"),
        Quote(text="In order to succeed, we must first believe that we can.", author="Nikos Kazantzakis"),
        Quote(text="Don't watch the clock; do what it does. Keep going.", author="Sam Levenson"),
        Quote(text="The only way to achieve the impossible is to believe it is possible.", author="Charles Kingsleigh"),
        Quote(text="Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author="Albert Schweitzer"),
        Quote(text="The only limit to our realization of tomorrow is our doubts of today.", author="Franklin D. Roosevelt"),
        Quote(text="In order to succeed, we must first believe that we can.", author="Nikos Kazantzakis"),
        Quote(text="Don't watch the clock; do what it does. Keep going.", author="Sam Levenson"),
        Quote(text="The only way to achieve the impossible is to believe it is possible.", author="Charles Kingsleigh"),
        Quote(text="Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author="Albert Schweitzer"),
        Quote(text="The only limit to our realization of tomorrow is our doubts of today.", author="Franklin D. Roosevelt"),
    ]),
    Category(name="Wisdom", quotes=[
        Quote(text="The only true wisdom is in knowing you know nothing.", author="Socrates"),
        Quote(text="Life is really simple, but we insist on making it complicated.", author="Confucius"),
        Quote(text="It is the mark of an educated mind to be able to entertain a thought without accepting it.", author="Aristotle"),
        Quote(text="The only thing we have to fear is fear itself.", author="Franklin D. Roosevelt"),
        Quote(text="In the end, it's not the years in your life that count. It's the life in your years.", author="Abraham Lincoln"),
        Quote(text="Knowing yourself is the beginning of all wisdom.", author="Aristotle"),
        Quote(text="The only way to do great work is to love what you do.", author="Steve Jobs"),
        Quote(text="Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author="Buddha"),
        Quote(text="We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", author="Plato"),
        Quote(text="Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author="Maya Angelou"),
        Quote(text="The journey of a thousand miles begins with one step.", author="Lao Tzu"),
        Quote(text="The only thing necessary for the triumph of evil is for good men to do nothing.", author="Edmund Burke"),
        Quote(text="You must be the change you wish to see in the world.", author="Mahatma Gandhi"),
        Quote(text="What lies behind us and what lies before us are tiny matters compared to what lies within us.", author="Ralph Waldo Emerson"),
        Quote(text="The mind is everything. What you think you become.", author="Buddha"),
        Quote(text="Knowing yourself is the beginning of all wisdom.", author="Aristotle"),
        Quote(text="The only way to do great work is to love what you do.", author="Steve Jobs"),
        Quote(text="Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author="Buddha"),
        Quote(text="We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", author="Plato"),
        Quote(text="Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author="Maya Angelou"),
        Quote(text="The journey of a thousand miles begins with one step.", author="Lao Tzu"),
        Quote(text="The only thing necessary for the triumph of evil is for good men to do nothing.", author="Edmund Burke"),
        Quote(text="You must be the change you wish to see in the world.", author="Mahatma Gandhi"),
        Quote(text="What lies behind us and what lies before us are tiny matters compared to what lies within us.", author="Ralph Waldo Emerson"),
        Quote(text="The mind is everything. What you think you become.", author="Buddha")
    ]),
    Category(name="Happiness", quotes=[
         Quote(text="The purpose of our lives is to be happy.", author="Dalai Lama"),
        Quote(text="Happiness is a choice, not a result. Nothing will make you happy until you choose to be happy.", author="Ralph Marston"),
        Quote(text="The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart.", author="Helen Keller"),
        Quote(text="The only thing that will make you happy is being happy with who you are, and not who people think you are.", author="Goldie Hawn"),
        Quote(text="Count your age by friends, not years. Count your life by smiles, not tears.", author="John Lennon"),
        Quote(text="Happiness is not something ready-made. It comes from your own actions.", author="Dalai Lama"),
        Quote(text="The most important thing is to enjoy your life—to be happy—it's all that matters.", author="Audrey Hepburn"),
        Quote(text="There is only one happiness in this life, to love and be loved.", author="George Sand"),
        Quote(text="The best way to cheer yourself up is to try to cheer somebody else up.", author="Mark Twain"),
        Quote(text="The happiness of your life depends upon the quality of your thoughts.", author="Marcus Aurelius"),
        Quote(text="Learn to value yourself, which means: fight for your happiness.", author="Ayn Rand"),
        Quote(text="Happiness is not something ready-made. It comes from your own actions.", author="Dalai Lama"),
        Quote(text="The most important thing is to enjoy your life—to be happy—it's all that matters.", author="Audrey Hepburn"),
        Quote(text="There is only one happiness in this life, to love and be loved.", author="George Sand"),
        Quote(text="The best way to cheer yourself up is to try to cheer somebody else up.", author="Mark Twain"),
        Quote(text="The happiness of your life depends upon the quality of your thoughts.", author="Marcus Aurelius"),
        Quote(text="Learn to value yourself, which means: fight for your happiness.", author="Ayn Rand"),
        Quote(text="Happiness is not something ready-made. It comes from your own actions.", author="Dalai Lama"),
        Quote(text="The most important thing is to enjoy your life—to be happy—it's all that matters.", author="Audrey Hepburn"),
        Quote(text="There is only one happiness in this life, to love and be loved.", author="George Sand"),
        Quote(text="The best way to cheer yourself up is to try to cheer somebody else up.", author="Mark Twain"),
        Quote(text="The happiness of your life depends upon the quality of your thoughts.", author="Marcus Aurelius")
    ]),
    Category(name="Love", quotes=[
        Quote(text="The best thing to hold onto in life is each other.", author="Audrey Hepburn"),
        Quote(text="Love is composed of a single soul inhabiting two bodies.", author="Aristotle"),
        Quote(text="Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", author="Lao Tzu"),
        Quote(text="Love is an endless mystery, for it has nothing else to explain it.", author="Rabindranath Tagore"),
        Quote(text="The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves.", author="Victor Hugo"),
        Quote(text="Love is like the wind, you can't see it but you can feel it.", author="Nicholas Sparks"),
        Quote(text="To love is nothing. To be loved is something. But to love and be loved, that’s everything.", author="T. Tolis"),
        Quote(text="Love is not just looking at each other, it's looking in the same direction.", author="Antoine de Saint-Exupéry"),
        Quote(text="The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart.", author="Helen Keller"),
        Quote(text="You know you're in love when you can't fall asleep because reality is finally better than your dreams.", author="Dr. Seuss"),
        Quote(text="A flower cannot blossom without sunshine, and man cannot live without love.", author="Max Muller"),
        Quote(text="Love is like the wind, you can't see it but you can feel it.", author="Nicholas Sparks"),
        Quote(text="To love is nothing. To be loved is something. But to love and be loved, that’s everything.", author="T. Tolis"),
        Quote(text="Love is not just looking at each other, it's looking in the same direction.", author="Antoine de Saint-Exupéry"),
        Quote(text="The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart.", author="Helen Keller"),
        Quote(text="You know you're in love when you can't fall asleep because reality is finally better than your dreams.", author="Dr. Seuss"),
        Quote(text="A flower cannot blossom without sunshine, and man cannot live without love.", author="Max Muller"),
        Quote(text="Love is like the wind, you can't see it but you can feel it.", author="Nicholas Sparks"),
        Quote(text="To love is nothing. To be loved is something. But to love and be loved, that’s everything.", author="T. Tolis"),
        Quote(text="Love is not just looking at each other, it's looking in the same direction.", author="Antoine de Saint-Exupéry"),
        Quote(text="The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart.", author="Helen Keller"),
        Quote(text="You know you're in love when you can't fall asleep because reality is finally better than your dreams.", author="Dr. Seuss"),
        Quote(text="A flower cannot blossom without sunshine, and man cannot live without love.", author="Max Muller")
    ]),
    Category(name="Courage", quotes=[
        Quote(text="Courage is not the absence of fear, but the triumph over it.", author="Nelson Mandela"),
        Quote(text="It does not matter how slowly you go as long as you do not stop.", author="Confucius"),
        Quote(text="The only place where success comes before work is in the dictionary.", author="Vidal Sassoon"),
        Quote(text="The future belongs to those who believe in the beauty of their dreams.", author="Eleanor Roosevelt"),
        Quote(text="Life is 10% what happens to us and 90% how we react to it.", author="Charles R. Swindoll"),
        Quote(text="Success is not final, failure is not fatal: It is the courage to continue that counts.", author="Winston Churchill"),
        Quote(text="Courage doesn't mean you don't get afraid. Courage means you don't let fear stop you.", author="Bethany Hamilton"),
        Quote(text="It takes courage to grow up and become who you really are.", author="E.E. Cummings"),
        Quote(text="Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.", author="Winston Churchill"),
        Quote(text="All our dreams can come true, if we have the courage to pursue them.", author="Walt Disney"),
        Quote(text="The only thing we have to fear is fear itself.", author="Franklin D. Roosevelt"),
        Quote(text="Courage doesn't mean you don't get afraid. Courage means you don't let fear stop you.", author="Bethany Hamilton"),
        Quote(text="It takes courage to grow up and become who you really are.", author="E.E. Cummings"),
        Quote(text="Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.", author="Winston Churchill"),
        Quote(text="All our dreams can come true, if we have the courage to pursue them.", author="Walt Disney"),
        Quote(text="The only thing we have to fear is fear itself.", author="Franklin D. Roosevelt"),
        Quote(text="Courage doesn't mean you don't get afraid. Courage means you don't let fear stop you.", author="Bethany Hamilton"),
        Quote(text="It takes courage to grow up and become who you really are.", author="E.E. Cummings"),
        Quote(text="Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.", author="Winston Churchill"),
        Quote(text="All our dreams can come true, if we have the courage to pursue them.", author="Walt Disney"),
        Quote(text="The only thing we have to fear is fear itself.", author="Franklin D. Roosevelt")
    ]),
    Category(name="Success", quotes=[
        Quote(text="Success is not final, failure is not fatal: It is the courage to continue that counts.", author="Winston Churchill"),
        Quote(text="Success consists of going from failure to failure without loss of enthusiasm.", author="Winston Churchill"),
        Quote(text="The only place where success comes before work is in the dictionary.", author="Vidal Sassoon"),
        Quote(text="Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author="Albert Schweitzer"),
        Quote(text="Success is not in what you have, but who you are.", author="Bo Bennett"),
        Quote(text="Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author="Albert Schweitzer"),
        Quote(text="Success is not in what you have, but who you are.", author="Bo Bennett"),
        Quote(text="Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author="Albert Schweitzer"),
        Quote(text="Success is not in what you have, but who you are.", author="Bo Bennett"),
        Quote(text="The only place where success comes before work is in the dictionary.", author="Vidal Sassoon"),
        Quote(text="Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author="Albert Schweitzer"),
        Quote(text="Success is not in what you have, but who you are.", author="Bo Bennett"),
        Quote(text="Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author="Albert Schweitzer"),
        Quote(text="Success is not in what you have, but who you are.", author="Bo Bennett"),
        Quote(text="The only place where success comes before work is in the dictionary.", author="Vidal Sassoon"),
        Quote(text="Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author="Albert Schweitzer"),
        Quote(text="Success is not in what you have, but who you are.", author="Bo Bennett"),
        Quote(text="Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author="Albert Schweitzer"),
        Quote(text="Success is not in what you have, but who you are.", author="Bo Bennett"),
        Quote(text="The only place where success comes before work is in the dictionary.", author="Vidal Sassoon"),
        Quote(text="Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author="Albert Schweitzer"),
        Quote(text="Success is not in what you have, but who you are.", author="Bo Bennett")
    ]),
    Category(name="Gratitude", quotes=[
        Quote(text="Gratitude is when memory is stored in the heart and not in the mind.", author="Lionel Hampton"),
        Quote(text="Gratitude is the healthiest of all human emotions. The more you express gratitude for what you have, the more likely you will have even more to express gratitude for.", author="Zig Ziglar"),
        Quote(text="Gratitude unlocks the fullness of life. It turns what we have into enough, and more. It turns denial into acceptance, chaos to order, confusion to clarity. It can turn a meal into a feast, a house into a home, a stranger into a friend.", author="Melody Beattie"),
        Quote(text="Gratitude is the fairest blossom which springs from the soul.", author="Henry Ward Beecher"),
        Quote(text="Feeling gratitude and not expressing it is like wrapping a present and not giving it.", author="William Arthur Ward"),
        Quote(text="Gratitude is the healthiest of all human emotions. The more you express gratitude for what you have, the more likely you will have even more to express gratitude for.", author="Zig Ziglar"),
        Quote(text="Gratitude unlocks the fullness of life. It turns what we have into enough, and more. It turns denial into acceptance, chaos to order, confusion to clarity. It can turn a meal into a feast, a house into a home, a stranger into a friend.", author="Melody Beattie"),
        Quote(text="Gratitude is the fairest blossom which springs from the soul.", author="Henry Ward Beecher"),
        Quote(text="Feeling gratitude and not expressing it is like wrapping a present and not giving it.", author="William Arthur Ward"),
        Quote(text="Gratitude is the healthiest of all human emotions. The more you express gratitude for what you have, the more likely you will have even more to express gratitude for.", author="Zig Ziglar"),
        Quote(text="Gratitude unlocks the fullness of life. It turns what we have into enough, and more. It turns denial into acceptance, chaos to order, confusion to clarity. It can turn a meal into a feast, a house into a home, a stranger into a friend.", author="Melody Beattie"),
        Quote(text="Gratitude is the fairest blossom which springs from the soul.", author="Henry Ward Beecher"),
        Quote(text="Feeling gratitude and not expressing it is like wrapping a present and not giving it.", author="William Arthur Ward"),
        Quote(text="Gratitude is the healthiest of all human emotions. The more you express gratitude for what you have, the more likely you will have even more to express gratitude for.", author="Zig Ziglar"),
        Quote(text="Gratitude unlocks the fullness of life. It turns what we have into enough, and more. It turns denial into acceptance, chaos to order, confusion to clarity. It can turn a meal into a feast, a house into a home, a stranger into a friend.", author="Melody Beattie"),
        Quote(text="Gratitude is the fairest blossom which springs from the soul.", author="Henry Ward Beecher"),
        Quote(text="Feeling gratitude and not expressing it is like wrapping a present and not giving it.", author="William Arthur Ward"),
        Quote(text="Gratitude is the healthiest of all human emotions. The more you express gratitude for what you have, the more likely you will have even more to express gratitude for.", author="Zig Ziglar"),
        Quote(text="Gratitude unlocks the fullness of life. It turns what we have into enough, and more. It turns denial into acceptance, chaos to order, confusion to clarity. It can turn a meal into a feast, a house into a home, a stranger into a friend.", author="Melody Beattie"),
        Quote(text="Gratitude is the fairest blossom which springs from the soul.", author="Henry Ward Beecher"),
        Quote(text="Feeling gratitude and not expressing it is like wrapping a present and not giving it.", author="William Arthur Ward")
    ]),
    Category(name="Creativity", quotes=[
        Quote(text="Creativity is intelligence having fun.", author="Albert Einstein"),
        Quote(text="The secret to creativity is knowing how to hide your sources.", author="Albert Einstein"),
        Quote(text="Creativity takes courage.", author="Henri Matisse"),
        Quote(text="You can't use up creativity. The more you use, the more you have.", author="Maya Angelou"),
        Quote(text="Imagination is the beginning of creation. You imagine what you desire, you will what you imagine, and at last, you create what you will.", author="George Bernard Shaw"),
        Quote(text="Creativity is contagious. Pass it on.", author="Albert Einstein"),
        Quote(text="Creativity is the power to connect the seemingly unconnected.", author="William Plomer"),
        Quote(text="Innovation distinguishes between a leader and a follower.", author="Steve Jobs"),
        Quote(text="The chief enemy of creativity is 'good' sense.", author="Pablo Picasso"),
        Quote(text="You can't wait for inspiration, you have to go after it with a club.", author="Jack London"),
        Quote(text="The desire to create is one of the deepest yearnings of the human soul.", author="Dieter F. Uchtdorf"),
        Quote(text="Creativity is just connecting things.", author="Steve Jobs"),
        Quote(text="Creativity is the ability to introduce order into the randomness of nature.", author="Eric Hoffer"),
        Quote(text="To be creative means to be in love with life. You can be creative only if you love life enough that you want to enhance its beauty, you want to bring a little more music to it, a little more poetry to it, a little more dance to it.", author="Osho"),
        Quote(text="You need chaos in your soul to give birth to a dancing star.", author="Friedrich Nietzsche"),
        Quote(text="Art is the most intense mode of individualism that the world has known.", author="Oscar Wilde"),
        Quote(text="Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep.", author="Scott Adams"),
        Quote(text="The true sign of intelligence is not knowledge but imagination.", author="Albert Einstein"),
        Quote(text="Every artist was first an amateur.", author="Ralph Waldo Emerson"),
        Quote(text="Creativity is more than just being different. Anybody can plan weird; that's easy. What's hard is to be as simple as Bach. Making the simple, awesomely simple, that's creativity.", author="Charles Mingus"),
        Quote(text="An essential aspect of creativity is not being afraid to fail.", author="Edwin Land"),
        Quote(text="The creative adult is the child who survived.", author="Ursula K. Le Guin"),
    ]),
    Category(name="Perseverance", quotes=[
        Quote(text="It does not matter how slowly you go as long as you do not stop.", author="Confucius"),
        Quote(text="Many of life's failures are people who did not realize how close they were to success when they gave up.", author="Thomas A. Edison"),
        Quote(text="Perseverance is not a long race; it is many short races one after the other.", author="Walter Elliot"),
        Quote(text="Perseverance, secret of all triumphs.", author="Victor Hugo"),
        Quote(text="The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", author="Vince Lombardi"),
        Quote(text="You are never too old to set another goal or to dream a new dream.", author="C.S. Lewis"),
        Quote(text="Perseverance is the hard work you do after you get tired of doing the hard work you already did.", author="Newt Gingrich"),
        Quote(text="With ordinary talent and extraordinary perseverance, all things are attainable.", author="Thomas Fowell Buxton"),
        Quote(text="Perseverance is failing nineteen times and succeeding the twentieth.", author="Julie Andrews"),
        Quote(text="Success is stumbling from failure to failure with no loss of enthusiasm.", author="Winston S. Churchill"),
        Quote(text="The only way to finish is to start.", author="Proverb"),
        Quote(text="Perseverance is not the absence of adversity, but the ability to continue despite it.", author="Unknown"),
        Quote(text="Perseverance is the hard work you do after you get tired of doing the hard work you already did.", author="Newt Gingrich"),
        Quote(text="It always seems impossible until it's done.", author="Nelson Mandela"),
        Quote(text="Perseverance is not a long race; it is many short races one after the other.", author="Walter Elliot"),
        Quote(text="I am not talented, I am obsessed.", author="Conor McGregor"),
        Quote(text="I will persist until I succeed.", author="Og Mandino"),
        Quote(text="It does not matter how slowly you go, so long as you do not stop.", author="Confucius"),
        Quote(text="Fall down seven times, get up eight.", author="Japanese Proverb"),
        Quote(text="I am not judged by the number of times I fail, but by the number of times I succeed: and the number of times I succeed is in direct proportion to the number of times I fail and keep trying.", author="Tom Hopkins"),
        Quote(text="Perseverance is not a long race; it is many short races one after another.", author="Walter Elliott"),
        Quote(text="It's not whether you get knocked down. It's whether you get up.", author="Vince Lombardi"),
    ]),
    Category(name="Kindness", quotes=[
        Quote(text="Kindness is a language which the deaf can hear and the blind can see.", author="Mark Twain"),
        Quote(text="No act of kindness, no matter how small, is ever wasted.", author="Aesop"),
        Quote(text="Be kind whenever possible. It is always possible.", author="Dalai Lama"),
        Quote(text="Kindness is the sunshine in which virtue grows.", author="Robert Green Ingersoll"),
        Quote(text="Kindness is the language which the deaf can hear and the blind can see.", author="Mark Twain"),
        Quote(text="Kindness is always fashionable, and always welcome.", author="Amelia Barr"),
        Quote(text="The simplest acts of kindness are by far more powerful then a thousand heads bowing in prayer.", author="Mahatma Gandhi"),
        Quote(text="Kindness is the light that dissolves all walls between souls, families, and nations.", author="Paramahansa Yogananda"),
        Quote(text="Kindness is the ability to know what the right thing to do is and having the courage to do it!!", author="Raktivist"),
        Quote(text="Be kind to unkind people, they need it the most.", author="Ashleigh Brilliant"),
        Quote(text="The world is full of kind people... If you can't find one, be one.", author="Unknown"),
        Quote(text="The best way to find yourself is to lose yourself in the service of others.", author="Mahatma Gandhi"),
        Quote(text="Kindness is the greatest wisdom.", author="Unknown"),
        Quote(text="Kindness is the golden chain by which society is bound together.", author="Johann Wolfgang von Goethe"),
        Quote(text="One kind word can change someone's entire day.", author="Unknown"),
        Quote(text="A single act of kindness throws out roots in all directions, and the roots spring up and make new trees.", author="Amelia Earhart"),
        Quote(text="Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.", author="Lao Tzu"),
        Quote(text="Kindness is free; let's pass it on.", author="Unknown"),
        Quote(text="Kindness is the universal language.", author="Unknown"),
        Quote(text="Kindness is the key to peace and happiness.", author="Unknown"),
        Quote(text="In a world where you can be anything, be kind.", author="Unknown"),
        Quote(text="Kindness begins with me.", author="Unknown"),
    ]),
    Category(name="Mindfulness", quotes=[
        Quote(text="The present moment is the only moment available to us, and it is the door to all moments.", author="Thich Nhat Hanh"),
        Quote(text="Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", author="Thich Nhat Hanh"),
        Quote(text="The most precious gift we can offer anyone is our attention. When mindfulness embraces those we love, they will bloom like flowers.", author="Thich Nhat Hanh"),
        Quote(text="Mindfulness is simply being aware of what is happening right now without wishing it were different; enjoying the pleasant without holding on when it changes (which it will); being with the unpleasant without fearing it will always be this way (which it won’t).", author="James Baraz"),
        Quote(text="When you realize nothing is lacking, the whole world belongs to you.", author="Lao Tzu"),
        Quote(text="If you want to conquer the anxiety of life, live in the moment, live in the breath.", author="Amit Ray"),
        Quote(text="Breathing in, I calm body and mind. Breathing out, I smile. Dwelling in the present moment I know this is the only moment.", author="Thich Nhat Hanh"),
        Quote(text="Mindfulness isn’t difficult, we just need to remember to do it.", author="Sharon Salzberg"),
        Quote(text="When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love.", author="Marcus Aurelius"),
        Quote(text="Drink your tea slowly and reverently, as if it is the axis on which the world earth revolves – slowly, evenly, without rushing toward the future.", author="Thich Nhat Hanh"),
        Quote(text="Mindfulness is about being fully awake in our lives. It is about perceiving the exquisite vividness of each moment. We also gain immediate access to our own powerful inner resources for insight, transformation, and healing.", author="Jon Kabat-Zinn"),
        Quote(text="Smile, breathe, and go slowly.", author="Thich Nhat Hanh"),
        Quote(text="The mind is everything. What you think you become.", author="Buddha"),
        Quote(text="This is the real secret of life - to be completely engaged with what you are doing in the here and now. And instead of calling it work, realize it is play.", author="Alan Watts"),
        Quote(text="In today’s rush, we all think too much — seek too much — want too much — and forget about the joy of just being.", author="Eckhart Tolle"),
        Quote(text="Realize deeply that the present moment is all you ever have. Make the Now the primary focus of your life.", author="Eckhart Tolle"),
        Quote(text="With mindfulness, you can establish yourself in the present in order to touch the wonders of life that are available in that moment.", author="Thich Nhat Hanh"),
        Quote(text="The moment one gives close attention to anything, even a blade of grass, it becomes a mysterious, awesome, indescribably magnificent world in itself.", author="Henry Miller"),
        Quote(text="Wherever you are, be there totally.", author="Eckhart Tolle"),
        Quote(text="There is no past or future for the enlightened. The past is remembered but not lived. The future is anticipated but not obsessed over. The present is what there is.", author="Deepak Chopra"),
        Quote(text="Your life is now. Seize it and make it amazing.", author="Unknown"),
        Quote(text="You must live in the present, launch yourself on every wave, find your eternity in each moment. Fools stand on their island of opportunities and look toward another land. There is no other land; there is no other life but this.", author="Henry David Thoreau"),
    ]),
    Category(name="Friendship", quotes=[
        Quote(text="Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.", author="C.S. Lewis"),
        Quote(text="A friend is someone who knows all about you and still loves you.", author="Elbert Hubbard"),
        Quote(text="Friendship is the only cement that will ever hold the world together.", author="Woodrow Wilson"),
        Quote(text="True friendship comes when the silence between two people is comfortable.", author="David Tyson"),
        Quote(text="The only way to have a friend is to be one.", author="Ralph Waldo Emerson"),
        Quote(text="Walking with a friend in the dark is better than walking alone in the light.", author="Helen Keller"),
        Quote(text="Friends are those rare people who ask how we are and then wait to hear the answer.", author="Ed Cunningham"),
        Quote(text="Friendship is always a sweet responsibility, never an opportunity.", author="Khalil Gibran"),
        Quote(text="A real friend is one who walks in when the rest of the world walks out.", author="Walter Winchell"),
        Quote(text="Friendship is the shadow of the evening, which increases with the setting sun of life.", author="Jean de La Fontaine"),
        Quote(text="A friend is what the heart needs all the time.", author="Henry Van Dyke"),
        Quote(text="A friend is one that knows you as you are, understands where you have been, accepts what you have become, and still, gently allows you to grow.", author="William Shakespeare"),
        Quote(text="Friendship is the only thing in the world concerning the usefulness of which all mankind are agreed.", author="Cicero"),
        Quote(text="Friendship marks a life even more deeply than love. Love risks degenerating into obsession, friendship is never anything but sharing.", author="Elie Wiesel"),
        Quote(text="Friendship is like a prism through which the many variations of beauty are revealed in our lives.", author="Unknown"),
        Quote(text="A friend is someone who gives you total freedom to be yourself.", author="Jim Morrison"),
        Quote(text="Friendship consists in forgetting what one gives and remembering what one receives.", author="Alexander Dumas"),
        Quote(text="The language of friendship is not words but meanings.", author="Henry David Thoreau"),
        Quote(text="Friendship is the inexpressible comfort of feeling safe with a person, having neither to weigh thoughts nor measure words.", author="George Eliot"),
        Quote(text="Friendship multiplies the good of life and divides the evil.", author="Baltasar Gracián"),
        Quote(text="Friendship is a plant of slow growth and must undergo and withstand the shocks of adversity before it is entitled to the appellation.", author="George Washington"),
        Quote(text="In the sweetness of friendship let there be laughter, for in the dew of little things the heart finds its morning and is refreshed.", author="Khalil Gibran"),
    ]),
    Category(name="Hope", quotes=[
        Quote(text="Hope is the thing with feathers that perches in the soul - and sings the tunes without the words - and never stops at all.", author="Emily Dickinson"),
        Quote(text="Hope is being able to see that there is light despite all of the darkness.", author="Desmond Tutu"),
        Quote(text="We must accept finite disappointment, but never lose infinite hope.", author="Martin Luther King, Jr."),
        Quote(text="Hope is important because it can make the present moment less difficult to bear. If we believe that tomorrow will be better, we can bear a hardship today.", author="Thich Nhat Hanh"),
        Quote(text="Keep your face always toward the sunshine—and shadows will fall behind you.", author="Walt Whitman"),
        Quote(text="There is some good in this world, and it's worth fighting for.", author="J.R.R. Tolkien"),
        Quote(text="In a time of destruction, create something.", author="Maxine Hong Kingston"),
        Quote(text="When you feel like giving up, remember why you held on for so long in the first place.", author="Unknown"),
        Quote(text="Once you choose hope, anything's possible.", author="Christopher Reeve"),
        Quote(text="Hope is the heartbeat of the soul.", author="Michelle Horst"),
        Quote(text="Hope itself is like a star- not to be seen in the sunshine of prosperity, and only to be discovered in the night of adversity.", author="Charles H. Spurgeon"),
        Quote(text="Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning.", author="Albert Einstein"),
        Quote(text="Hope begins in the dark, the stubborn hope that if you just show up and try to do the right thing, the dawn will come. You wait and watch and work: you don't give up.", author="Anne Lamott"),
        Quote(text="Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for.", author="Epicurus"),
        Quote(text="You may not always have a comfortable life and you will not always be able to solve all of the world's problems at once but don't ever underestimate the importance you can have because history has shown us that courage can be contagious and hope can take on a life of its own.", author="Michelle Obama"),
        Quote(text="Hope is like the sun, which, as we journey toward it, casts the shadow of our burden behind us.", author="Samuel Smiles"),
        Quote(text="When the world says, 'Give up,' hope whispers, 'Try it one more time.'", author="Unknown"),
        Quote(text="Hope is being able to see that there is light despite all of the darkness.", author="Desmond Tutu"),
        Quote(text="There is no medicine like hope, no incentive so great, and no tonic so powerful as expectation of something tomorrow.", author="Orison Swett Marden"),
        Quote(text="When you're at the end of your rope, tie a knot and hold on.", author="Theodore Roosevelt"),
        Quote(text="The darkest nights produce the brightest stars.", author="Unknown"),
        Quote(text="Hope is a waking dream.", author="Aristotle"),
    ]),
    Category(name="Dreams", quotes=[
        Quote(text="All our dreams can come true, if we have the courage to pursue them.", author="Walt Disney"),
        Quote(text="The future belongs to those who believe in the beauty of their dreams.", author="Eleanor Roosevelt"),
        Quote(text="Dreams are illustrations... from the book your soul is writing about you.", author="Marsha Norman"),
        Quote(text="A dreamer is one who can only find his way by moonlight, and his punishment is that he sees the dawn before the rest of the world.", author="Oscar Wilde"),
        Quote(text="You are never too old to set another goal or to dream a new dream.", author="C.S. Lewis"),
        Quote(text="The only thing that will stop you from fulfilling your dreams is you.", author="Tom Bradley"),
        Quote(text="Dream as if you'll live forever, live as if you'll die today.", author="James Dean"),
        Quote(text="Reality is wrong. Dreams are for real.", author="Tupac Shakur"),
        Quote(text="Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.", author="Langston Hughes"),
        Quote(text="The future belongs to those who believe in the beauty of their dreams.", author="Eleanor Roosevelt"),
        Quote(text="Dreams are the touchstones of our characters.", author="Henry David Thoreau"),
        Quote(text="The only thing worse than starting something and failing... is not starting something.", author="Seth Godin"),
        Quote(text="You see things; and you say, 'Why?' But I dream things that never were; and I say, 'Why not?'", author="George Bernard Shaw"),
        Quote(text="To accomplish great things, we must not only act, but also dream, not only plan, but also believe.", author="Anatole France"),
        Quote(text="A dream doesn't become reality through magic; it takes sweat, determination and hard work.", author="Colin Powell"),
        Quote(text="Whatever you do, or dream you can, begin it. Boldness has genius and power and magic in it.", author="Johann Wolfgang von Goethe"),
        Quote(text="Dream big and dare to fail.", author="Norman Vaughan"),
        Quote(text="Success is not final, failure is not fatal: It is the courage to continue that counts.", author="Winston Churchill"),
        Quote(text="Dreams are extremely important. You can't do it unless you imagine it.", author="George Lucas"),
        Quote(text="The only thing worse than starting something and failing... is not starting something.", author="Seth Godin"),
    ]),
    Category(name="Leadership", quotes=[
        Quote(text="The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.", author="Ronald Reagan"),
        Quote(text="Leadership and learning are indispensable to each other.", author="John F. Kennedy"),
        Quote(text="Leadership is the art of giving people a platform for spreading ideas that work.", author="Seth Godin"),
        Quote(text="The function of leadership is to produce more leaders, not more followers.", author="Ralph Nader"),
        Quote(text="A leader is one who knows the way, goes the way, and shows the way.", author="John C. Maxwell"),
        Quote(text="Innovation distinguishes between a leader and a follower.", author="Steve Jobs"),
        Quote(text="The price of greatness is responsibility.", author="Winston Churchill"),
        Quote(text="The mediocre teacher tells. The good teacher explains. The superior teacher demonstrates. The great teacher inspires.", author="William Arthur Ward"),
        Quote(text="A good leader takes a little more than his share of the blame, a little less than his share of the credit.", author="Arnold H. Glasow"),
        Quote(text="A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves.", author="Lao Tzu"),
        Quote(text="Leadership is the capacity to translate vision into reality.", author="Warren Bennis"),
        Quote(text="If your actions inspire others to dream more, learn more, do more and become more, you are a leader.", author="John Quincy Adams"),
        Quote(text="A true leader has the confidence to stand alone, the courage to make tough decisions, and the compassion to listen to the needs of others. He does not set out to be a leader, but becomes one by the equality of his actions and the integrity of his intent.", author="Douglas MacArthur"),
        Quote(text="Management is doing things right; leadership is doing the right things.", author="Peter Drucker"),
        Quote(text="Leadership is not about being in charge. It is about taking care of those in your charge.", author="Simon Sinek"),
        Quote(text="You manage things; you lead people.", author="Grace Murray Hopper"),
        Quote(text="A genuine leader is not a searcher for consensus but a molder of consensus.", author="Martin Luther King Jr."),
        Quote(text="Leadership is not about titles, positions, or flowcharts. It is about one life influencing another.", author="John C. Maxwell"),
        Quote(text="The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.", author="Ronald Reagan"),
        Quote(text="Leadership is the art of giving people a platform for spreading ideas that work.", author="Seth Godin"),
        Quote(text="Leadership is not about being in charge. It is about taking care of those in your charge.", author="Simon Sinek"),
    ]),
    Category(name="Adventure", quotes=[
        Quote(text="Life is either a daring adventure or nothing at all.", author="Helen Keller"),
        Quote(text="Adventure is worthwhile.", author="Aesop"),
        Quote(text="The biggest adventure you can take is to live the life of your dreams.", author="Oprah Winfrey"),
        Quote(text="Every man's life ends the same way. It is only the details of how he lived and how he died that distinguish one man from another.", author="Ernest Hemingway"),
        Quote(text="It is never too late to be what you might have been.", author="George Eliot"),
        Quote(text="The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.", author="Eleanor Roosevelt"),
        Quote(text="The only way to deal with fear is to face it.", author="L. Frank Baum"),
        Quote(text="Adventure is allowing the unexpected to happen to you. Exploration is experiencing what you have not experienced before.", author="Richard Aldington"),
        Quote(text="Adventure isn't hanging off a rope on the side of a mountain. Adventure is an attitude that we must apply to the day to day obstacles in life.", author="John Amatt"),
        Quote(text="To live would be an awfully big adventure.", author="J.M. Barrie"),
        Quote(text="Adventure is not outside man; it is within.", author="George Eliot"),
        Quote(text="Do not stop thinking of life as an adventure. You have no security unless you can live bravely, excitingly, imaginatively.", author="Eleanor Roosevelt"),
        Quote(text="The only question in life is whether or not you are going to answer a hearty 'YES!' to your adventure.", author="Joseph Campbell"),
        Quote(text="Adventure is not outside man; it is within.", author="George Eliot"),
        Quote(text="You are braver than you believe, stronger than you seem, and smarter than you think.", author="A.A. Milne"),
        Quote(text="Adventure is worthwhile.", author="Aesop"),
        ]),
]

# Add instances to the session
for category in categories:
    db_storage.new(category)
    for quote in category.quotes:
        db_storage.new(quote)

# Commit changes
db_storage.save()
